---
# Project
site_name: ndfc-python
site_url: https://allenrobel.github.io/ndfc-python
site_author: Allen Robel
site_description: >-
  Python classes and example scripts to interact with Cisco's Nexus Dashboard
  Fabric Controller

# Repo
repo_name: allenrobel/ndfc-python
repo_url: https://github.com/allenrobel/ndfc-python
edit_uri: blob/mkdocs/docs/
remote_branch: main

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Setup:
      - Clone the repositories: setup/clone-the-repositories.md
      - Update your PYTHONPATH: setup/update-your-pythonpath.md
      - Enable logging: setup/enable-logging.md
      - Running the example scripts: setup/running-the-example-scripts.md
      - Using Ansible Vault: setup/using-ansible-vault.md
  - Scripts:
      - credentials.py: scripts/credentials.md
      - device_info.py: scripts/device_info.md
      - fabric_details.py: scripts/fabric_details.md
      - network_create.py: scripts/network_create.md
      - network_delete.py: scripts/network_delete.md
      - reachability.py: scripts/reachability.md
  - Classes:
      - Overview: classes/overview.md
      - Log: classes/Log.md
      - NetworkCreate: classes/NetworkCreate.md
      - NetworkDelete: classes/NetworkDelete.md
