site_name: ndfc-python
site_url: https://allenrobel.github.io/ndfc-python/docs
theme:
  name: material
  palette:
    scheme: default
    primary: deep orange
repo_name: allenrobel/ndfc-python
repo_url: https://github.com/allenrobel/ndfc-python
edit_uri: blob/mkdocs/docs/
remote_branch: main
