site_name: ndfc-python
nav:
  - Home: index.md
  - About: about.md
  - Usage: usage.md
  - Scripts: scripts.md
  - Classes: classes.md
theme: mkdocs
repo_name: allenrobel/ndfc-python
repo_url: https://github.com/allenrobel/ndfc-python
edit_uri: blob/mkdocs/docs/
remote_branch: mkdocs
