---
config:
  - switch_name: LE1
    fabric_name: SITE1
  - switch_name: SP1
    fabric_name: SITE1
  - switch_name: BG1
    fabric_name: SITE1
  - switch_name: LE2
    fabric_name: SITE2
  - switch_name: SP2
    fabric_name: SITE2
  - switch_name: BG2
    fabric_name: SITE2
