---
config:
  # SITE1 LE1
  - detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE1
    freeform_config: []
    instance_values: ""
    network_name: v1n1
    serial_number: 96KWEIQE2HC
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
  # SITE2 LE2
  - detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE2
    freeform_config: []
    instance_values: ""
    network_name: v1n1
    serial_number: 9OW9132EH2M
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
