# SITE1 / SITE2
---
config:

  # BG1
  - fabric_name: SITE1
    switch_name: BG1
    vrf_name: v1

  # LE1
  - fabric_name: SITE1
    switch_name: LE1
    vrf_name: v1

  # BG2
  - fabric_name: SITE2
    switch_name: BG2
    vrf_name: v1

  # LE2
  - fabric_name: SITE2
    switch_name: LE2
    vrf_name: v1
