---
config:
  - switch_name: LE1
    fabric_name: SITE1
    access_vlan: ""
    admin_state: True
    bpduguard_enabled: True
    desc: "Eth1/2: Connected to HO1"
    enable_netflow: False
    freeform_config: ""
    interface_name: Ethernet1/2
    mtu: jumbo
    netflow_monitor: ""
    porttype_fast_enabled: True
    ptp: False
    speed: Auto
