---
config:
  - deployment: true
    detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE1
    freeform_config: []
    instance_values: ""
    mso_created: false
    mso_set_vlan: false
    network_name: ndfc-python-net1
    serial_number: 96KWEIQE2HC
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
  - deployment: true
    detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE2
    freeform_config: []
    instance_values: ""
    mso_created: false
    mso_set_vlan: false
    network_name: ndfc-python-net1
    serial_number: 9OW9132EH2M
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
