---
MD013:
  line_length: 256            # Line length 80 is far to short
MD004: false                  # ul-style, * is allowed by material
MD007: false                  # ul-indent, material not indenting with 2 spaces
MD040: false                  # Allow ``` blocks with no language specified
MD046: false                  # Disable Expected: indented; Actual: fenced

