---
config:
  - switch_name: LE3
    fabric_name: SITE3
  - switch_name: SP3
    fabric_name: SITE3
  - switch_name: BG3
    fabric_name: SITE3
  - switch_name: VP3
    fabric_name: SITE4
  - switch_name: VP4
    fabric_name: SITE4
  - switch_name: SP4
    fabric_name: SITE4
  - switch_name: BG4
    fabric_name: SITE4
