---
config:
  # SITE3 LE3
  - switch_name: LE3
    detach_switch_ports:
      - Ethernet1/2
    fabric_name: SITE3
    network_name: v1n1
    vlan: 2301
  # SITE4 VP3
  - switch_name: VP3
    detach_switch_ports:
      - Ethernet1/2
    fabric_name: SITE4
    network_name: v1n1
    vlan: 2301
  # SITE4 VP4
  - switch_name: VP4
    detach_switch_ports:
      - Ethernet1/2
    fabric_name: SITE4
    network_name: v1n1
    vlan: 2301
