---
config:
  - fabric_name: MSD
    network_name: v1n1
    enable_ir: True
    gateway_ip_address: 192.1.1.1/24
    network_id: 30001
    suppress_arp: False
    vlan_id: 2301
    vrf_name: v1
  - fabric_name: MSD
    network_name: v1n2
    enable_ir: True
    gateway_ip_address: 192.2.1.1/24
    network_id: 30002
    suppress_arp: False
    vlan_id: 2302
    vrf_name: v1
