---
config:
  # SITE3 LE3
  - switch_name: LE3
    detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE3
    freeform_config: []
    instance_values: ""
    network_name: v1n1
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
  # SITE4 VP3
  - switch_name: VP3
    detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE4
    freeform_config: []
    instance_values: ""
    network_name: v1n1
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
  # SITE4 VP4
  - switch_name: VP4
    detach_switch_ports: []
    dot1q_vlan: ""
    extension_values: ""
    fabric_name: SITE4
    freeform_config: []
    instance_values: ""
    network_name: v1n1
    switch_ports:
      - Ethernet1/2
    untagged: true
    tor_ports: []
    vlan: 2301
