---
config:
  - switch_name: LE3
    fabric_name: SITE3 # fabric_name needed to retrieve switch information
    description: management vrf static route to syslog server
    entity_name: SWITCH
    entity_type: SWITCH
    priority: 200
    source: ""
    template_name: vrf_static_route
    nv_pairs:
      IP_PREFIX: 192.168.7.1/32
      NEXT_HOP_IP: 192.168.12.1
      VRF_NAME: management
