# SITE3 / SITE4
---
config:

  # BG3
  - fabric_name: SITE3
    serial_number: 92RZ2OMQCNC
    vrf_name: v1

  # LE3
  - fabric_name: SITE3
    serial_number: 93M2LB9V37J
    vrf_name: v1

  # BG4
  - fabric_name: SITE4
    serial_number: 92BX6HD7BG0
    vrf_name: v1

  # LE4
  - fabric_name: SITE4
    serial_number: 9XS0QJEAI69
    vrf_name: v1
