# SITE3 / SITE4
# For vPC peers, only one switch of the pair needs to be included.
# The configuration for the vPC switch must include the peer_switch_name parameter.
# See VP3 below for an example.
---
config:

  # BG3
  - switch_name: BG3
    extension_values:
      - auto_vrf_lite_flag: true
        dot1q_id: "3"
        if_name: Ethernet1/1
        ip_mask: "10.33.0.1/30"
        ipv6_mask: "2010::10:33:0:1/64"
        neighbor_asn: "65002"
        neighbor_ip: 10.33.0.2
        ipv6_neighbor: "2010::10:33:0:2"
        peer_vrf_name: v1
    fabric_name: SITE3
    freeform_config: []
    instance_values:
      loopback_id: 111
      loopback_ip_address: 10.19.0.141
      loopback_ip_v6_address: ""
      switch_route_target_import_evpn: ""
      switch_route_target_export_evpn: ""
    vlan: 2001
    vrf_name: v1

  # LE3
  - switch_name: LE3
    extension_values:
      - {}
    fabric_name: SITE3
    freeform_config: []
    instance_values:
      loopback_id: 111
      loopback_ip_address: 10.19.0.131
      loopback_ip_v6_address: ""
      switch_route_target_import_evpn: ""
      switch_route_target_export_evpn: ""
    vlan: 2001
    vrf_name: v1

  # BG4
  - switch_name: BG4
    extension_values:
      - auto_vrf_lite_flag: true
        dot1q_id: "3"
        if_name: Ethernet1/1
        ip_mask: "10.33.0.2/30"
        ipv6_mask: "2010::10:33:0:2/64"
        neighbor_asn: "65001"
        neighbor_ip: 10.33.0.1
        ipv6_neighbor: "2010::10:33:0:1"
        peer_vrf_name: v1
    fabric_name: SITE4
    freeform_config: []
    instance_values:
      loopback_id: 111
      loopback_ip_address: 10.19.0.142
      loopback_ip_v6_address: ""
      switch_route_target_import_evpn: ""
      switch_route_target_export_evpn: ""
    vlan: 2001
    vrf_name: v1

  # VP3
  - switch_name: VP3
    peer_switch_name: VP4
    extension_values:
      - {}
    fabric_name: SITE4
    freeform_config: []
    instance_values: {}
    vlan: 2001
    vrf_name: v1
