# SITE3 / SITE4
---
config:

  # BG3
  - fabric_name: SITE3
    switch_name: BG3
    vrf_name: v1

  # LE3
  - fabric_name: SITE3
    switch_name: LE3
    vrf_name: v1

  # BG4
  - fabric_name: SITE4
    switch_name: BG4
    vrf_name: v1

  # LE4
  - fabric_name: SITE4
    switch_name: LE4
    vrf_name: v1
